version: '3.9'

volumes:
  minhaterra-api-volume-1:
    name: minhaterra-api-volume-1

services:
  postgres:
    container_name: postgres-minhaterra-api
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - minhaterra-api-volume-1:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=vfOyiyNEDLTkLnoomUujiEKznNGYdEfO
      - POSTGRES_USER=postgres
      - POSTGRES_DB=minhaterra-api-database