const CONSTANTS = {
  PASSWORD_RESET_TOKEN_LENGTH: 32,
  PASSWORD_RESET_EXPIRY_HOURS: 2,
  CONTACT_VERIFICATION_EXPIRY_HOURS: 12,
  DEFAULT_AMOUNT_OF_SALT_ITERATIONS: 128,
  NO_REPLY_EMAIL_ADDRESS: 'no-reply@minhaserra.com',
  JWT_EXPIRATION_HOURS: 6,
  JWT_ALGORITHM: 'HS512',
  MAX_ADDRESSES_PER_USER: 10,
  JSON_BODY_LIMIT: '11mb',
  MAX_BASE64_IMAGE_SIZE: 8000000,
  DEFAULT_MAX_STRING_SIZE: 100,
  MAX_IMAGES_PER_PRODUCT: 7,
};

export default CONSTANTS;
